[package]
name = "ostrya-cli"
description = "Command-line front-end for the ostrya library"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "ostrya"
path = "src/main.rs"

[features]
default = ["smol"]
smol = ["ostrya/smol", "ostrya-rt/smol"]
tokio = ["ostrya/tokio", "ostrya-rt/tokio"]

[dependencies]
ostrya = { path = "../ostrya", default-features = false }
ostrya-rt = { workspace = true }
clap = { version = "4", features = ["derive"] }
