[workspace]
resolver = "3"
members = [
    "crates/ostrya-gvariant",
    "crates/ostrya-core",
    "crates/ostrya-composefs",
    "crates/ostrya-rt",
    "crates/ostrya-sys",
    "crates/ostrya",
    "crates/ostrya-cli",
    "crates/ostrya-conformance",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.92"
license = "MIT"
repository = "https://github.com/growler/ostrya"
readme = "README.md"

[workspace.dependencies]
ostrya-gvariant = { path = "crates/ostrya-gvariant", version = "0.0.1" }
ostrya-core = { path = "crates/ostrya-core", version = "0.0.1" }
ostrya-composefs = { path = "crates/ostrya-composefs", version = "0.0.1" }
ostrya-rt = { path = "crates/ostrya-rt", version = "0.0.1", default-features = false }
ostrya-sys = { path = "crates/ostrya-sys", version = "0.0.1" }
