[package]
name = "ostrya-core"
description = "ostree object model, checksums, and on-disk format primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
ostrya-gvariant = { workspace = true }
sha2 = { version = "0.10", default-features = false, features = ["std"] }
