[package]
name = "ostrya"
description = "Pure-Rust async reimplementation of the ostree repository library"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[features]
default = ["smol"]
smol = ["ostrya-rt/smol"]
tokio = ["ostrya-rt/tokio"]

[dependencies]
ostrya-core = { workspace = true }
ostrya-composefs = { workspace = true }
ostrya-rt = { workspace = true }
thiserror = "2"
rustix = { version = "1", default-features = false, features = ["std", "fs"] }
sha2 = { version = "0.10", default-features = false, features = ["std"] }
async-compression = { version = "0.4", default-features = false, features = [
    "deflate",
    "futures-io",
] }
pin-project-lite = "0.2"
futures-io = "0.3"

[dev-dependencies]
ostrya-rt = { workspace = true }
futures-lite = "2"
