#!/usr/bin/env bash
#
# Golden-fixture generator for the ostree Rust port.
#
# Drives the `ostree` tool as a black box to emit reference bytes into
# tests/fixtures/generated/. The output is the correctness reference the port
# is checked against: the tool must read what the port writes, and the port
# must read what the tool wrote here.
#
# Determinism. A fixed branch, a fixed commit timestamp, owner 0:0, no xattrs,
# and explicit file modes make every content-addressed object and every ref
# byte-stable, so re-running yields byte-identical tracked files. (The bare
# epoch form `--timestamp=1700000000` is rejected by the tool; the `@epoch`
# form is used instead.)
#
# Invariant. Object identity, and therefore the dirtree and commit checksums,
# are independent of repository mode. The script commits the same tree in each
# mode and fails if the resulting commit checksums are not identical.
#
# Clean-room note. The `ostree` tool is treated purely as a black box: only its
# command output and the bytes it writes on disk inform the port. Its source is
# never consulted. See CLAUDE.md, "Licensing and clean-room discipline".

set -euo pipefail

# --- deterministic knobs ---
BRANCH="test/main"
SUBJECT="fixture commit"
TIMESTAMP="@1700000000" # 2023-11-14 22:13:20 UTC
OWNER_UID=0
OWNER_GID=0
MODES=(archive bare-user)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="$SCRIPT_DIR/generated"

if ! command -v ostree >/dev/null 2>&1; then
    echo "error: the 'ostree' tool is not on PATH; cannot generate fixtures" >&2
    exit 1
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# --- build the deterministic source tree ---
# A regular file, an empty file, a nested regular file, and a symlink exercise
# the file-object, empty-payload, nested-dirtree, and symlink paths.
SRC="$WORK/tree"
mkdir -p "$SRC/subdir"
printf 'hello ostree\n' >"$SRC/hello.txt"
: >"$SRC/empty.txt"
printf 'nested\n' >"$SRC/subdir/nested.txt"
ln -s hello.txt "$SRC/link"
chmod 0644 "$SRC/hello.txt" "$SRC/empty.txt" "$SRC/subdir/nested.txt"
chmod 0755 "$SRC/subdir"

# --- regenerate output from scratch ---
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

declare -A CHECKSUM
for mode in "${MODES[@]}"; do
    repo="$WORK/repo-$mode"
    ostree --repo="$repo" init "--mode=$mode" >/dev/null
    checksum="$(ostree --repo="$repo" commit \
        --branch="$BRANCH" --subject="$SUBJECT" \
        --owner-uid="$OWNER_UID" --owner-gid="$OWNER_GID" \
        --no-xattrs --timestamp="$TIMESTAMP" "$SRC")"
    CHECKSUM["$mode"]="$checksum"

    # Copy the deterministic parts only; the lock file and tmp staging are
    # transient and are left out.
    dst="$OUT_DIR/$mode/repo"
    mkdir -p "$dst"
    cp -a "$repo/config" "$dst/config"
    cp -a "$repo/objects" "$dst/objects"
    cp -a "$repo/refs" "$dst/refs"
done

# --- assert the cross-mode commit-identity invariant ---
first="${MODES[0]}"
for mode in "${MODES[@]}"; do
    if [[ "${CHECKSUM[$mode]}" != "${CHECKSUM[$first]}" ]]; then
        echo "error: cross-mode commit identity broken:" >&2
        for m in "${MODES[@]}"; do echo "  $m = ${CHECKSUM[$m]}" >&2; done
        exit 1
    fi
done

# --- bare fixture for the write path ---
# Bare mode stores the logical uid/gid/mode on the object inode, so a faithful
# write needs to own those ids. The owner is the invoking uid/gid so that an
# unprivileged test can reproduce the ownership the tool applies. Its object
# checksums therefore depend on the invoking user and are not part of the
# cross-mode identity invariant above; the write-path test cross-checks bare
# against a repository the tool builds at test time.
BARE_UID="$(id -u)"
BARE_GID="$(id -g)"
bare_repo="$WORK/repo-bare"
ostree --repo="$bare_repo" init --mode=bare >/dev/null
ostree --repo="$bare_repo" commit \
    --branch="$BRANCH" --subject="$SUBJECT" \
    --owner-uid="$BARE_UID" --owner-gid="$BARE_GID" \
    --no-xattrs --timestamp="$TIMESTAMP" "$SRC" >/dev/null
bare_dst="$OUT_DIR/bare/repo"
mkdir -p "$bare_dst"
cp -a "$bare_repo/config" "$bare_dst/config"
cp -a "$bare_repo/objects" "$bare_dst/objects"
cp -a "$bare_repo/refs" "$bare_dst/refs"

COMMIT="${CHECKSUM[$first]}"
CONTENT="$(ostree --repo="$WORK/repo-$first" show "$COMMIT" |
    sed -n 's/^ContentChecksum:[[:space:]]*//p')"
OSTREE_VERSION="$(ostree --version | awk -F"'" '/Version:/ {print $2}')"

cat >"$OUT_DIR/MANIFEST" <<EOF
# Golden fixtures for the ostree Rust port, generated by generate.sh.
# Generator: ostree ${OSTREE_VERSION} (black box).
# Deterministic inputs: branch=${BRANCH} timestamp=${TIMESTAMP} owner=${OWNER_UID}:${OWNER_GID} no-xattrs.
# The bare/ fixture uses owner=${BARE_UID}:${BARE_GID} (the invoking user) and is
# therefore owner-specific, not part of the cross-mode commit-identity guarantee.
branch=${BRANCH}
commit=${COMMIT}
content_checksum=${CONTENT}
modes=${MODES[*]}
bare_owner=${BARE_UID}:${BARE_GID}
EOF

echo "generated fixtures in ${OUT_DIR}"
echo "  commit (identical across ${MODES[*]}): ${COMMIT}"
echo "  bare/ fixture owner ${BARE_UID}:${BARE_GID} (owner-specific)"
